pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'bug-002',
                    url: 'https://github.com/veerendrabijib/practice-session1.git'
            }
        }

    }

    post {
        always {
            publishHTML([
    allowMissing: false,
    alwaysLinkToLastBuild: true,
    keepAll: true,
    reportDir: '.',
    reportFiles: 'demo.html',
    reportName: 'Demo HTML Page',
    reportTitles: 'Demo HTML Page'
      ])

        }
        success {
            echo 'Build Successful'
        }
        failure {
            echo 'Build Failed'
        }
    }
}
