pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'bug-002',
                    url: 'https://github.com/veerendrabijib/practice-session1.git'
            }
        }

    }

    post {
        always {
            publishHTML([
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,

                // IMPORTANT FIX
                reportDir: 'bijib',
                reportFiles: 'demo.html',
                reportName: 'Demo HTML Page',

                // BYPASS JENKINS WRAPPER
                useWrapperFileDirectly: true
                 ])

        }
        success {
            echo 'Build Successful'
        }
        failure {
            echo 'Build Failed'
        }
    }
}
